### ISSUE TITLE
[dglo on 2007-05-24 15:23:32] : pDAQ: globalTrigger - running at SPS regularly gets a NullPointerException

### ISSUE THREAD

**Issue by dglo** [dglo/oldtrigger#13]
This exception showed up in runs 107870 through 107875:

Exception in thread "HKN1Splicer" java.lang.NullPointerException
        at java.util.Vector.size(Vector.java:774)
        at icecube.daq.trigger.control.GlobalTriggerHandler.process(GlobalTriggerHandler.java:377)
        at icecube.daq.trigger.control.GlobalTriggerManager.execute(GlobalTriggerManager.java:186)
        at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:326)
        at java.lang.Thread.run(Thread.java:799)

**Comment by dglo** [comment]
[dglo on 2007-05-24 17:42:38]
Sending        src/main/java/icecube/daq/trigger/control/GlobalTriggerHandler.java
Transmitting file data .
Committed revision 1453.
