### ISSUE TITLE
[dglo on 2011-03-11 23:12:01] : pDAQ: trigger - global trigger component getting recycled payload errors

### ISSUE THREAD

**Issue by dglo** [dglo/oldtrigger#152]
The global trigger spits out errors like:

globalTrigger icecube.daq.oldpayload.impl.Payload-Main-globalTrigger#0 ERROR [2011-01-28 18:18:53.808] Not copying 0-length payload (type 9)
globalTrigger icecube.daq.oldpayload.impl.CompositePayloadFactory-Main-globalTrigger#0 ERROR [2011-01-28 18:18:53.814] Cannot deep-copy composite payload 1 of 1 (type 9, length 0)
globalTrigger icecube.daq.trigger.algorithm.ThroughputTrigger-Main-globalTrigger#0 ERROR [2011-01-28 18:18:53.815] Couldn't wrap trigger
java.lang.NullPointerException: mtGlobalTrigEventPayload is NULL in wrapTrigger()
	at icecube.daq.trigger.algorithm.AbstractGlobalTrigger.wrapTrigger(AbstractGlobalTrigger.java:75)
	at icecube.daq.trigger.algorithm.ThroughputTrigger.runTrigger(ThroughputTrigger.java:61)
	at icecube.daq.trigger.control.GlobalTriggerHandler.reprocess(GlobalTriggerHandler.java:499)
	at icecube.daq.trigger.control.GlobalTriggerHandler$MainThread.run(GlobalTriggerHandler.java:985)
	at java.lang.Thread.run(Thread.java:736)

**Comment by dglo** [comment]
[dglo on 2011-03-12 00:06:34]
svn commit -m"Issue 4661: Examine all requests for overlap, not just later requests" src/main/java/icecube/daq/trigger/control/TriggerInput.java 
Sending        src/main/java/icecube/daq/trigger/control/TriggerInput.java
Transmitting file data .
Committed revision 12771.

**Comment by dglo** [comment]
[dglo on 2011-06-14 19:51:06]
Jupiter is dead, long live Jupiter2 (at least until Kirala)
