### ISSUE TITLE
[dglo on 2011-03-21 22:10:50] : pDAQ: trigger - bug in trigger algorithm can kill the trigger handler

### ISSUE THREAD

**Issue by dglo** [dglo/oldtrigger#155]
During testing on SPTS, the VolumeTrigger threw a NullPointerException which killed the detector:

Exception in thread "Main-inIceTrigger#0" java.lang.NullPointerException
	at icecube.daq.trigger.algorithm.LogicalChannelVT.fromHitPayload(VolumeTrigger.java:309)
	at icecube.daq.trigger.algorithm.VolumeTrigger.processHitQueue(VolumeTrigger.java:215)
	at icecube.daq.trigger.algorithm.VolumeTrigger.runTrigger(VolumeTrigger.java:188)
	at icecube.daq.trigger.control.TriggerHandler.reprocess(TriggerHandler.java:431)
	at icecube.daq.trigger.control.TriggerHandler$MainThread.run(TriggerHandler.java:875)
	at java.lang.Thread.run(Thread.java:636)

**Comment by dglo** [comment]
[dglo on 2011-03-21 22:15:21]
svn commit -m"Issue 4686: Don't let trigger algorithm bugs kill the detector"
Sending        src/main/java/icecube/daq/trigger/control/GlobalTriggerHandler.java
Sending        src/main/java/icecube/daq/trigger/control/TriggerHandler.java
Transmitting file data ..
Committed revision 12797.

**Comment by dglo** [comment]
[dglo on 2011-06-14 19:51:14]
Jupiter is dead, long live Jupiter2 (at least until Kirala)
